# Generated by Django 2.2.1 on 2019-05-30 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 30, 15, 50, 8, 304219)),
        ),
    ]
